theme = "lynx"
title = "John Espinosa"
languageCode = "en-us"
baseUrl = "https://revotek.github.io"
googleAnalytics = ""

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  image = "azprofile.jpg"
  alternative = "John Espinosa | Software Engineer | Learner | Leader"
  links = [
    { github = "https://github.com/revotek" },
    { linkedin = "https://www.linkedin.com/in/johnespinosasr/" }
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true

[params]
  keywords = "revotek,johnespinosa,john,espinosa,software,engineer,developer,profile,azure"
  robots = "index,follow"
